name: Build and Deploy API Gateway 

on:
  push:
    branches:
      - main
      - qa
      - develop
    paths:
      - 'api-gateway/**'       # Trigger when files in api-gateway folder change
      - 'helmcharts/api-gateway/**'        

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment dynamically
        id: set-env
        run: |
          if [[ "${BRANCH}" == "main" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          elif [[ "${BRANCH}" == "qa" ]]; then
            echo "env=qa" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image 
        env: 
          IMAGE_TAG: "${{ secrets.API_ECR_REPOSITORY }}:api-gateway-${{ github.sha }}" 
        run: |
          docker build -t $IMAGE_TAG -f api-gateway/Dockerfile api-gateway

      - name: Push Docker image to ECR 
        env: 
          IMAGE_TAG: "${{ secrets.API_ECR_REPOSITORY }}:api-gateway-${{ github.sha }}" 
        run: | 
          docker push $IMAGE_TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name demo-cluster --region ${{ secrets.AWS_REGION }}

      - name: Check Kubernetes config
        run: |
          cat ~/.kube/config
          kubectl cluster-info

      - name: Deploy API Gateway with Helm
        run: |
          ENV=${{ steps.set-env.outputs.env }}
          NAMESPACE=$ENV
          helm upgrade --install api-gateway helmcharts/api-gateway \
            --namespace $NAMESPACE
            --set image.tag=api-gateway-${{ github.sha }}
